"""initial schema

Revision ID: 2ea39b27b42d
Revises: 
Create Date: 2026-07-17 15:00:58.895823
"""
from alembic import op
import sqlalchemy as sa


revision = '2ea39b27b42d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('contact_email', sa.String(length=160), nullable=True),
    sa.Column('atrium_client_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exercise_library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('muscle_group', sa.String(length=60), nullable=True),
    sa.Column('day_types_json', sa.Text(), nullable=False),
    sa.Column('equipment', sa.String(length=60), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('leave_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('annual_balance', sa.Float(), nullable=False),
    sa.Column('accrual_type', sa.String(length=20), nullable=False),
    sa.Column('requires_approval', sa.String(length=40), nullable=False),
    sa.Column('carry_over_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('shift_start', sa.String(length=5), nullable=False),
    sa.Column('shift_end', sa.String(length=5), nullable=False),
    sa.Column('break_duration_min', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('google_sub', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('profile_pic_url', sa.String(length=400), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('shift_start', sa.String(length=5), nullable=True),
    sa.Column('shift_end', sa.String(length=5), nullable=True),
    sa.Column('hired_date', sa.Date(), nullable=True),
    sa.Column('monthly_salary', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_google_sub'), ['google_sub'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('attendance_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('device', sa.String(length=40), nullable=False),
    sa.Column('late_status', sa.String(length=16), nullable=True),
    sa.Column('late_minutes', sa.Integer(), nullable=False),
    sa.Column('late_reason', sa.String(length=200), nullable=True),
    sa.Column('handover_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_events_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_events_user_id'), ['user_id'], unique=False)

    op.create_table('attendance_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('old_value', sa.String(length=120), nullable=True),
    sa.Column('new_value', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_requests_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('table_name', sa.String(length=60), nullable=False),
    sa.Column('record_id', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('old_value_json', sa.Text(), nullable=True),
    sa.Column('new_value_json', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_table_name'), ['table_name'], unique=False)

    op.create_table('daily_attendance_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('clock_in', sa.DateTime(), nullable=True),
    sa.Column('clock_out', sa.DateTime(), nullable=True),
    sa.Column('break_start', sa.DateTime(), nullable=True),
    sa.Column('break_end', sa.DateTime(), nullable=True),
    sa.Column('break_duration_min', sa.Integer(), nullable=False),
    sa.Column('total_work_hours', sa.Float(), nullable=False),
    sa.Column('overtime_minutes', sa.Integer(), nullable=False),
    sa.Column('overtime_approved', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('handover_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_summary_user_date')
    )
    with op.batch_alter_table('daily_attendance_summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_attendance_summary_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_attendance_summary_user_id'), ['user_id'], unique=False)

    op.create_table('gym_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day_type', sa.String(length=16), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gym_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gym_logs_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_gym_logs_user_id'), ['user_id'], unique=False)

    op.create_table('leave_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('used', sa.Float(), nullable=False),
    sa.Column('remaining', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_balances_user_id'), ['user_id'], unique=False)

    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_days', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_requests_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('payroll_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('bonus', sa.Float(), nullable=False),
    sa.Column('deduction', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('finalized', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period', name='uq_payroll_user_period')
    )
    with op.batch_alter_table('payroll_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_entries_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_entries_user_id'), ['user_id'], unique=False)

    op.create_table('qr_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qr_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qr_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_qr_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('system_settings',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('campaign', sa.String(length=160), nullable=True),
    sa.Column('content_type', sa.String(length=80), nullable=True),
    sa.Column('account_manager_id', sa.Integer(), nullable=True),
    sa.Column('assigned_team_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('labels_json', sa.Text(), nullable=False),
    sa.Column('checklist_json', sa.Text(), nullable=False),
    sa.Column('atrium_visible', sa.Boolean(), nullable=False),
    sa.Column('deliverable_url', sa.String(length=500), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('client_facing_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_assigned_team_id'), ['assigned_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    op.create_table('atrium_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('client_response', sa.String(length=40), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('revision_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('atrium_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atrium_approvals_task_id'), ['task_id'], unique=False)

    op.create_table('gym_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gym_log_id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(length=120), nullable=False),
    sa.Column('muscle_group', sa.String(length=60), nullable=True),
    sa.Column('weight_value', sa.Float(), nullable=False),
    sa.Column('weight_unit', sa.String(length=8), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('set_type', sa.String(length=16), nullable=False),
    sa.Column('sets_json', sa.Text(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gym_log_id'], ['gym_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gym_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gym_exercises_gym_log_id'), ['gym_log_id'], unique=False)

    op.create_table('task_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachments_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_comments_task_id'), ['task_id'], unique=False)

    op.create_table('task_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('field_changed', sa.String(length=60), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_history_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_history_task_id'))

    op.drop_table('task_history')
    with op.batch_alter_table('task_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_comments_task_id'))

    op.drop_table('task_comments')
    with op.batch_alter_table('gym_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gym_exercises_gym_log_id'))

    op.drop_table('gym_exercises')
    with op.batch_alter_table('atrium_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atrium_approvals_task_id'))

    op.drop_table('atrium_approvals')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_client_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_assigned_to_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_assigned_team_id'))

    op.drop_table('tasks')
    op.drop_table('system_settings')
    with op.batch_alter_table('qr_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qr_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_qr_tokens_token'))

    op.drop_table('qr_tokens')
    with op.batch_alter_table('payroll_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_payroll_entries_period'))

    op.drop_table('payroll_entries')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))

    op.drop_table('notifications')
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_leave_requests_status'))

    op.drop_table('leave_requests')
    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_balances_user_id'))

    op.drop_table('leave_balances')
    with op.batch_alter_table('gym_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gym_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_gym_logs_date'))

    op.drop_table('gym_logs')
    with op.batch_alter_table('daily_attendance_summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_attendance_summary_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_attendance_summary_date'))

    op.drop_table('daily_attendance_summary')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_table_name'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('attendance_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_requests_status'))

    op.drop_table('attendance_requests')
    with op.batch_alter_table('attendance_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_events_date'))

    op.drop_table('attendance_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_google_sub'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('leave_types')
    op.drop_table('exercise_library')
    op.drop_table('clients')
    # ### end Alembic commands ###
